window.esdocSearchIndex = [
  [
    "kleros-api/src/contracts/abstractcontract.js~abstractcontract",
    "class/src/contracts/AbstractContract.js~AbstractContract.html",
    "<span>AbstractContract</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/AbstractContract.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/abstractions/arbitrable.js~arbitrablecontract",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html",
    "<span>ArbitrableContract</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/abstractions/Arbitrable.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html",
    "<span>ArbitrableTransaction</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/arbitrable/ArbitrableTransaction.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/abstractions/arbitrator.js~arbitrator",
    "class/src/contracts/abstractions/Arbitrator.js~Arbitrator.html",
    "<span>Arbitrator</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/abstractions/Arbitrator.js</span>",
    "class"
  ],
  [
    "kleros-api/src/resources/auth.js~auth",
    "class/src/resources/Auth.js~Auth.html",
    "<span>Auth</span> <span class=\"search-result-import-path\">kleros-api/src/resources/Auth.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/rng/blockhashrng.js~blockhashrng",
    "class/src/contracts/implementations/RNG/BlockHashRNG.js~BlockHashRNG.html",
    "<span>BlockHashRNG</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/RNG/BlockHashRNG.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/contractimplementation.js~contractimplementation",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html",
    "<span>ContractImplementation</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/ContractImplementation.js</span>",
    "class"
  ],
  [
    "kleros-api/src/resources/disputes.js~disputes",
    "class/src/resources/Disputes.js~Disputes.html",
    "<span>Disputes</span> <span class=\"search-result-import-path\">kleros-api/src/resources/Disputes.js</span>",
    "class"
  ],
  [
    "kleros-api/src/utils/eventlistener.js~eventlistener",
    "class/src/utils/EventListener.js~EventListener.html",
    "<span>EventListener</span> <span class=\"search-result-import-path\">kleros-api/src/utils/EventListener.js</span>",
    "class"
  ],
  [
    "kleros-api/src/kleros.js~kleros",
    "class/src/kleros.js~Kleros.html",
    "<span>Kleros</span> <span class=\"search-result-import-path\">kleros-api/src/kleros.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/arbitrator/klerospoc.js~klerospoc",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html",
    "<span>KlerosPOC</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/arbitrator/KlerosPOC.js</span>",
    "class"
  ],
  [
    "kleros-api/src/resources/notifications.js~notifications",
    "class/src/resources/Notifications.js~Notifications.html",
    "<span>Notifications</span> <span class=\"search-result-import-path\">kleros-api/src/resources/Notifications.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html",
    "<span>PinakionPOC</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/PNK/PinakionPOC.js</span>",
    "class"
  ],
  [
    "kleros-api/src/utils/promisequeue.js~promisequeue",
    "function/index.html#static-function-PromiseQueue",
    "<span>PromiseQueue</span> <span class=\"search-result-import-path\">kleros-api/src/utils/PromiseQueue.js</span>",
    "function"
  ],
  [
    "kleros-api/src/utils/storeproviderwrapper.js~storeproviderwrapper",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html",
    "<span>StoreProviderWrapper</span> <span class=\"search-result-import-path\">kleros-api/src/utils/StoreProviderWrapper.js</span>",
    "class"
  ],
  [
    "kleros-api/src/utils/web3wrapper.js~web3wrapper",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html",
    "<span>Web3Wrapper</span> <span class=\"search-result-import-path\">kleros-api/src/utils/Web3Wrapper.js</span>",
    "class"
  ],
  [
    "kleros-api/src/utils/delegatecalls.js~delegatecalls",
    "function/index.html#static-function-delegateCalls",
    "<span>delegateCalls</span> <span class=\"search-result-import-path\">kleros-api/src/utils/delegateCalls.js</span>",
    "function"
  ],
  [
    "kleros-api/src/utils/deploycontractasync.js~deploycontractasync",
    "function/index.html#static-function-deployContractAsync",
    "<span>deployContractAsync</span> <span class=\"search-result-import-path\">kleros-api/src/utils/deployContractAsync.js</span>",
    "function"
  ],
  [
    "kleros-api/src/utils/isrequired.js~isrequired",
    "function/index.html#static-function-isRequired",
    "<span>isRequired</span> <span class=\"search-result-import-path\">kleros-api/src/utils/isRequired.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/contracts/abstractcontract.js",
    "file/src/contracts/AbstractContract.js.html",
    "src/contracts/AbstractContract.js",
    "file"
  ],
  [
    "src/contracts/abstractcontract.js~abstractcontract#_storeprovider",
    "class/src/contracts/AbstractContract.js~AbstractContract.html#instance-member-_StoreProvider",
    "src/contracts/AbstractContract.js~AbstractContract#_StoreProvider",
    "member"
  ],
  [
    "src/contracts/abstractcontract.js~abstractcontract#_contractimplementation",
    "class/src/contracts/AbstractContract.js~AbstractContract.html#instance-member-_contractImplementation",
    "src/contracts/AbstractContract.js~AbstractContract#_contractImplementation",
    "member"
  ],
  [
    "src/contracts/abstractcontract.js~abstractcontract#constructor",
    "class/src/contracts/AbstractContract.js~AbstractContract.html#instance-constructor-constructor",
    "src/contracts/AbstractContract.js~AbstractContract#constructor",
    "method"
  ],
  [
    "src/contracts/abstractcontract.js~abstractcontract#setstoreproviderinstance",
    "class/src/contracts/AbstractContract.js~AbstractContract.html#instance-member-setStoreProviderInstance",
    "src/contracts/AbstractContract.js~AbstractContract#setStoreProviderInstance",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js",
    "file/src/contracts/ContractImplementation.js.html",
    "src/contracts/ContractImplementation.js",
    "file"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_web3wrapper",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_Web3Wrapper",
    "src/contracts/ContractImplementation.js~ContractImplementation#_Web3Wrapper",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_contractloadedrejecter",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_contractLoadedRejecter",
    "src/contracts/ContractImplementation.js~ContractImplementation#_contractLoadedRejecter",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_contractloadedresolver",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_contractLoadedResolver",
    "src/contracts/ContractImplementation.js~ContractImplementation#_contractLoadedResolver",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_instantiatecontractifexistsasync",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_instantiateContractIfExistsAsync",
    "src/contracts/ContractImplementation.js~ContractImplementation#_instantiateContractIfExistsAsync",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_load",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_load",
    "src/contracts/ContractImplementation.js~ContractImplementation#_load",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_loadingcontractinstance",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_loadingContractInstance",
    "src/contracts/ContractImplementation.js~ContractImplementation#_loadingContractInstance",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_newloadingpromise",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_newLoadingPromise",
    "src/contracts/ContractImplementation.js~ContractImplementation#_newLoadingPromise",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#artifact",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-artifact",
    "src/contracts/ContractImplementation.js~ContractImplementation#artifact",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#constructor",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-constructor-constructor",
    "src/contracts/ContractImplementation.js~ContractImplementation#constructor",
    "method"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#contractaddress",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-contractAddress",
    "src/contracts/ContractImplementation.js~ContractImplementation#contractAddress",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#contractinstance",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-contractInstance",
    "src/contracts/ContractImplementation.js~ContractImplementation#contractInstance",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#getblock",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-getBlock",
    "src/contracts/ContractImplementation.js~ContractImplementation#getBlock",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#getcontractaddress",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-getContractAddress",
    "src/contracts/ContractImplementation.js~ContractImplementation#getContractAddress",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#getweb3provider",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-getWeb3Provider",
    "src/contracts/ContractImplementation.js~ContractImplementation#getWeb3Provider",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#isloading",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-isLoading",
    "src/contracts/ContractImplementation.js~ContractImplementation#isLoading",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#loadcontract",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-loadContract",
    "src/contracts/ContractImplementation.js~ContractImplementation#loadContract",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#setcontractinstance",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-setContractInstance",
    "src/contracts/ContractImplementation.js~ContractImplementation#setContractInstance",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrable.js",
    "file/src/contracts/abstractions/Arbitrable.js.html",
    "src/contracts/abstractions/Arbitrable.js",
    "file"
  ],
  [
    "src/contracts/abstractions/arbitrable.js~arbitrablecontract#deploy",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html#instance-member-deploy",
    "src/contracts/abstractions/Arbitrable.js~ArbitrableContract#deploy",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrable.js~arbitrablecontract#getcontractsforuser",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html#instance-member-getContractsForUser",
    "src/contracts/abstractions/Arbitrable.js~ArbitrableContract#getContractsForUser",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrable.js~arbitrablecontract#getdata",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html#instance-member-getData",
    "src/contracts/abstractions/Arbitrable.js~ArbitrableContract#getData",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrable.js~arbitrablecontract#getdatafromstore",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html#instance-member-getDataFromStore",
    "src/contracts/abstractions/Arbitrable.js~ArbitrableContract#getDataFromStore",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrable.js~arbitrablecontract#getevidenceforarbitrablecontract",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html#instance-member-getEvidenceForArbitrableContract",
    "src/contracts/abstractions/Arbitrable.js~ArbitrableContract#getEvidenceForArbitrableContract",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrable.js~arbitrablecontract#submitevidence",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html#instance-member-submitEvidence",
    "src/contracts/abstractions/Arbitrable.js~ArbitrableContract#submitEvidence",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrator.js",
    "file/src/contracts/abstractions/Arbitrator.js.html",
    "src/contracts/abstractions/Arbitrator.js",
    "file"
  ],
  [
    "src/contracts/abstractions/arbitrator.js~arbitrator#buypnk",
    "class/src/contracts/abstractions/Arbitrator.js~Arbitrator.html#instance-member-buyPNK",
    "src/contracts/abstractions/Arbitrator.js~Arbitrator#buyPNK",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrator.js~arbitrator#getdisputesforuser",
    "class/src/contracts/abstractions/Arbitrator.js~Arbitrator.html#instance-member-getDisputesForUser",
    "src/contracts/abstractions/Arbitrator.js~Arbitrator#getDisputesForUser",
    "member"
  ],
  [
    "src/contracts/abstractions/index.js",
    "file/src/contracts/abstractions/index.js.html",
    "src/contracts/abstractions/index.js",
    "file"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js",
    "file/src/contracts/implementations/PNK/PinakionPOC.js.html",
    "src/contracts/implementations/PNK/PinakionPOC.js",
    "file"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc#constructor",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html#instance-constructor-constructor",
    "src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc#getdata",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html#instance-member-getData",
    "src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC#getData",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc#setkleros",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html#instance-member-setKleros",
    "src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC#setKleros",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc#transferownership",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html#instance-member-transferOwnership",
    "src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC#transferOwnership",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc.deploy",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html#static-member-deploy",
    "src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/index.js",
    "file/src/contracts/implementations/PNK/index.js.html",
    "src/contracts/implementations/PNK/index.js",
    "file"
  ],
  [
    "src/contracts/implementations/rng/blockhashrng.js",
    "file/src/contracts/implementations/RNG/BlockHashRNG.js.html",
    "src/contracts/implementations/RNG/BlockHashRNG.js",
    "file"
  ],
  [
    "src/contracts/implementations/rng/blockhashrng.js~blockhashrng#constructor",
    "class/src/contracts/implementations/RNG/BlockHashRNG.js~BlockHashRNG.html#instance-constructor-constructor",
    "src/contracts/implementations/RNG/BlockHashRNG.js~BlockHashRNG#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/rng/blockhashrng.js~blockhashrng.deploy",
    "class/src/contracts/implementations/RNG/BlockHashRNG.js~BlockHashRNG.html#static-member-deploy",
    "src/contracts/implementations/RNG/BlockHashRNG.js~BlockHashRNG.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/rng/index.js",
    "file/src/contracts/implementations/RNG/index.js.html",
    "src/contracts/implementations/RNG/index.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js",
    "file/src/contracts/implementations/arbitrable/ArbitrableTransaction.js.html",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#calltimeoutpartya",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-callTimeOutPartyA",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#callTimeOutPartyA",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#calltimeoutpartyb",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-callTimeOutPartyB",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#callTimeOutPartyB",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#constructor",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-constructor-constructor",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#getdata",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-getData",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#getData",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#getrulingoptions",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-getRulingOptions",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#getRulingOptions",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#pay",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-pay",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#pay",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#payarbitrationfeebypartya",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-payArbitrationFeeByPartyA",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#payArbitrationFeeByPartyA",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#payarbitrationfeebypartyb",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-payArbitrationFeeByPartyB",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#payArbitrationFeeByPartyB",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#submitevidence",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-submitEvidence",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#submitEvidence",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction.deploy",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#static-member-deploy",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/index.js",
    "file/src/contracts/implementations/arbitrable/index.js.html",
    "src/contracts/implementations/arbitrable/index.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js",
    "file/src/contracts/implementations/arbitrator/KlerosPOC.js.html",
    "src/contracts/implementations/arbitrator/KlerosPOC.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#activatepnk",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-activatePNK",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#activatePNK",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#appealruling",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-appealRuling",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#appealRuling",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#buypnk",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-buyPNK",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#buyPNK",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#canruledispute",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-canRuleDispute",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#canRuleDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#constructor",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-constructor-constructor",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#currentrulingfordispute",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-currentRulingForDispute",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#currentRulingForDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#executeruling",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-executeRuling",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#executeRuling",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getamountofjurorsfordispute",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getAmountOfJurorsForDispute",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getAmountOfJurorsForDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getarbitrationcost",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getArbitrationCost",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getArbitrationCost",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getdata",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getData",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getData",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getdeadlineforopendispute",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getDeadlineForOpenDispute",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getDeadlineForOpenDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getdispute",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getDispute",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getdisputesforjuror",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getDisputesForJuror",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getDisputesForJuror",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getdrawsforjuror",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getDrawsForJuror",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getDrawsForJuror",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getopendisputesforsession",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getOpenDisputesForSession",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getOpenDisputesForSession",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getpnkbalance",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getPNKBalance",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getPNKBalance",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getperiod",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getPeriod",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getPeriod",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#getsession",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getSession",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getSession",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#gettimeforperiod",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-getTimeForPeriod",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#getTimeForPeriod",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#isjurordrawnfordispute",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-isJurorDrawnForDispute",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#isJurorDrawnForDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#passperiod",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-passPeriod",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#passPeriod",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#repartitionjurortokens",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-repartitionJurorTokens",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#repartitionJurorTokens",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#submitvotes",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-submitVotes",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#submitVotes",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc.deploy",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#static-member-deploy",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/index.js",
    "file/src/contracts/implementations/arbitrator/index.js.html",
    "src/contracts/implementations/arbitrator/index.js",
    "file"
  ],
  [
    "src/contracts/implementations/index.js",
    "file/src/contracts/implementations/index.js.html",
    "src/contracts/implementations/index.js",
    "file"
  ],
  [
    "src/contracts/index.js",
    "file/src/contracts/index.js.html",
    "src/contracts/index.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/kleros.js",
    "file/src/kleros.js.html",
    "src/kleros.js",
    "file"
  ],
  [
    "src/kleros.js~kleros#arbitrable",
    "class/src/kleros.js~Kleros.html#instance-member-arbitrable",
    "src/kleros.js~Kleros#arbitrable",
    "member"
  ],
  [
    "src/kleros.js~kleros#arbitrator",
    "class/src/kleros.js~Kleros.html#instance-member-arbitrator",
    "src/kleros.js~Kleros#arbitrator",
    "member"
  ],
  [
    "src/kleros.js~kleros#auth",
    "class/src/kleros.js~Kleros.html#instance-member-auth",
    "src/kleros.js~Kleros#auth",
    "member"
  ],
  [
    "src/kleros.js~kleros#constructor",
    "class/src/kleros.js~Kleros.html#instance-constructor-constructor",
    "src/kleros.js~Kleros#constructor",
    "method"
  ],
  [
    "src/kleros.js~kleros#disputes",
    "class/src/kleros.js~Kleros.html#instance-member-disputes",
    "src/kleros.js~Kleros#disputes",
    "member"
  ],
  [
    "src/kleros.js~kleros#eventlistener",
    "class/src/kleros.js~Kleros.html#instance-member-eventListener",
    "src/kleros.js~Kleros#eventListener",
    "member"
  ],
  [
    "src/kleros.js~kleros#notifications",
    "class/src/kleros.js~Kleros.html#instance-member-notifications",
    "src/kleros.js~Kleros#notifications",
    "member"
  ],
  [
    "src/kleros.js~kleros#setarbitrablecontractaddress",
    "class/src/kleros.js~Kleros.html#instance-member-setArbitrableContractAddress",
    "src/kleros.js~Kleros#setArbitrableContractAddress",
    "member"
  ],
  [
    "src/kleros.js~kleros#setstoreprovider",
    "class/src/kleros.js~Kleros.html#instance-member-setStoreProvider",
    "src/kleros.js~Kleros#setStoreProvider",
    "member"
  ],
  [
    "src/kleros.js~kleros#stopwatchingforevents",
    "class/src/kleros.js~Kleros.html#instance-member-stopWatchingForEvents",
    "src/kleros.js~Kleros#stopWatchingForEvents",
    "member"
  ],
  [
    "src/kleros.js~kleros#storewrapper",
    "class/src/kleros.js~Kleros.html#instance-member-storeWrapper",
    "src/kleros.js~Kleros#storeWrapper",
    "member"
  ],
  [
    "src/kleros.js~kleros#watchforevents",
    "class/src/kleros.js~Kleros.html#instance-member-watchForEvents",
    "src/kleros.js~Kleros#watchForEvents",
    "member"
  ],
  [
    "src/kleros.js~kleros#web3wrapper",
    "class/src/kleros.js~Kleros.html#instance-member-web3Wrapper",
    "src/kleros.js~Kleros#web3Wrapper",
    "member"
  ],
  [
    "src/resources/auth.js",
    "file/src/resources/Auth.js.html",
    "src/resources/Auth.js",
    "file"
  ],
  [
    "src/resources/auth.js~auth#_storeproviderinstance",
    "class/src/resources/Auth.js~Auth.html#instance-member-_StoreProviderInstance",
    "src/resources/Auth.js~Auth#_StoreProviderInstance",
    "member"
  ],
  [
    "src/resources/auth.js~auth#_web3wrapper",
    "class/src/resources/Auth.js~Auth.html#instance-member-_Web3Wrapper",
    "src/resources/Auth.js~Auth#_Web3Wrapper",
    "member"
  ],
  [
    "src/resources/auth.js~auth#constructor",
    "class/src/resources/Auth.js~Auth.html#instance-constructor-constructor",
    "src/resources/Auth.js~Auth#constructor",
    "method"
  ],
  [
    "src/resources/auth.js~auth#getnewauthtoken",
    "class/src/resources/Auth.js~Auth.html#instance-member-getNewAuthToken",
    "src/resources/Auth.js~Auth#getNewAuthToken",
    "member"
  ],
  [
    "src/resources/auth.js~auth#setauthtoken",
    "class/src/resources/Auth.js~Auth.html#instance-member-setAuthToken",
    "src/resources/Auth.js~Auth#setAuthToken",
    "member"
  ],
  [
    "src/resources/auth.js~auth#setstoreproviderinstance",
    "class/src/resources/Auth.js~Auth.html#instance-member-setStoreProviderInstance",
    "src/resources/Auth.js~Auth#setStoreProviderInstance",
    "member"
  ],
  [
    "src/resources/auth.js~auth#signmessage",
    "class/src/resources/Auth.js~Auth.html#instance-member-signMessage",
    "src/resources/Auth.js~Auth#signMessage",
    "member"
  ],
  [
    "src/resources/auth.js~auth#validateauthtoken",
    "class/src/resources/Auth.js~Auth.html#instance-member-validateAuthToken",
    "src/resources/Auth.js~Auth#validateAuthToken",
    "member"
  ],
  [
    "src/resources/disputes.js",
    "file/src/resources/Disputes.js.html",
    "src/resources/Disputes.js",
    "file"
  ],
  [
    "src/resources/disputes.js~disputes#_arbitrableinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_ArbitrableInstance",
    "src/resources/Disputes.js~Disputes#_ArbitrableInstance",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_arbitratorinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_ArbitratorInstance",
    "src/resources/Disputes.js~Disputes#_ArbitratorInstance",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_storeproviderinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_StoreProviderInstance",
    "src/resources/Disputes.js~Disputes#_StoreProviderInstance",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_storeappealdeadline",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_storeAppealDeadline",
    "src/resources/Disputes.js~Disputes#_storeAppealDeadline",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_storedisputeruledattimestamp",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_storeDisputeRuledAtTimestamp",
    "src/resources/Disputes.js~Disputes#_storeDisputeRuledAtTimestamp",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_storenewdisputehandler",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_storeNewDisputeHandler",
    "src/resources/Disputes.js~Disputes#_storeNewDisputeHandler",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_storetokensmovedforjuror",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_storeTokensMovedForJuror",
    "src/resources/Disputes.js~Disputes#_storeTokensMovedForJuror",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#constructor",
    "class/src/resources/Disputes.js~Disputes.html#instance-constructor-constructor",
    "src/resources/Disputes.js~Disputes#constructor",
    "method"
  ],
  [
    "src/resources/disputes.js~disputes#getdatafordispute",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-getDataForDispute",
    "src/resources/Disputes.js~Disputes#getDataForDispute",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#getdisputefromstore",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-getDisputeFromStore",
    "src/resources/Disputes.js~Disputes#getDisputeFromStore",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#registerstoreupdateeventlisteners",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-registerStoreUpdateEventListeners",
    "src/resources/Disputes.js~Disputes#registerStoreUpdateEventListeners",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#setarbitrableinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-setArbitrableInstance",
    "src/resources/Disputes.js~Disputes#setArbitrableInstance",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#setarbitratorinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-setArbitratorInstance",
    "src/resources/Disputes.js~Disputes#setArbitratorInstance",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#setstoreproviderinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-setStoreProviderInstance",
    "src/resources/Disputes.js~Disputes#setStoreProviderInstance",
    "member"
  ],
  [
    "src/resources/notifications.js",
    "file/src/resources/Notifications.js.html",
    "src/resources/Notifications.js",
    "file"
  ],
  [
    "src/resources/notifications.js~notifications#_arbitrableinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_ArbitrableInstance",
    "src/resources/Notifications.js~Notifications#_ArbitrableInstance",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_arbitratorinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_ArbitratorInstance",
    "src/resources/Notifications.js~Notifications#_ArbitratorInstance",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_storeproviderinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_StoreProviderInstance",
    "src/resources/Notifications.js~Notifications#_StoreProviderInstance",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_appealpossiblehandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_appealPossibleHandler",
    "src/resources/Notifications.js~Notifications#_appealPossibleHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_appealingdecisionhandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_appealingDecisionHandler",
    "src/resources/Notifications.js~Notifications#_appealingDecisionHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_arbitrationrewardhandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_arbitrationRewardHandler",
    "src/resources/Notifications.js~Notifications#_arbitrationRewardHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_createhandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_createHandler",
    "src/resources/Notifications.js~Notifications#_createHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_createnotification",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_createNotification",
    "src/resources/Notifications.js~Notifications#_createNotification",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_disputecreationhandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_disputeCreationHandler",
    "src/resources/Notifications.js~Notifications#_disputeCreationHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_getcontracts",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_getContracts",
    "src/resources/Notifications.js~Notifications#_getContracts",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_getdisputes",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_getDisputes",
    "src/resources/Notifications.js~Notifications#_getDisputes",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_newnotification",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_newNotification",
    "src/resources/Notifications.js~Notifications#_newNotification",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_newperiodhandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_newPeriodHandler",
    "src/resources/Notifications.js~Notifications#_newPeriodHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_requirestoreprovider",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_requireStoreProvider",
    "src/resources/Notifications.js~Notifications#_requireStoreProvider",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_sendpushnotification",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_sendPushNotification",
    "src/resources/Notifications.js~Notifications#_sendPushNotification",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_tokenshifthandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_tokenShiftHandler",
    "src/resources/Notifications.js~Notifications#_tokenShiftHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#constructor",
    "class/src/resources/Notifications.js~Notifications.html#instance-constructor-constructor",
    "src/resources/Notifications.js~Notifications#constructor",
    "method"
  ],
  [
    "src/resources/notifications.js~notifications#getstatefulnotifications",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-getStatefulNotifications",
    "src/resources/Notifications.js~Notifications#getStatefulNotifications",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#getstorednotifications",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-getStoredNotifications",
    "src/resources/Notifications.js~Notifications#getStoredNotifications",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#getunreadstorednotifications",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-getUnreadStoredNotifications",
    "src/resources/Notifications.js~Notifications#getUnreadStoredNotifications",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#markstorednotificationasread",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-markStoredNotificationAsRead",
    "src/resources/Notifications.js~Notifications#markStoredNotificationAsRead",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#registerarbitratornotifications",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-registerArbitratorNotifications",
    "src/resources/Notifications.js~Notifications#registerArbitratorNotifications",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#setarbitrableinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-setArbitrableInstance",
    "src/resources/Notifications.js~Notifications#setArbitrableInstance",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#setarbitratorinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-setArbitratorInstance",
    "src/resources/Notifications.js~Notifications#setArbitratorInstance",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#setstoreproviderinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-setStoreProviderInstance",
    "src/resources/Notifications.js~Notifications#setStoreProviderInstance",
    "member"
  ],
  [
    "src/resources/index.js",
    "file/src/resources/index.js.html",
    "src/resources/index.js",
    "file"
  ],
  [
    "src/utils/eventlistener.js",
    "file/src/utils/EventListener.js.html",
    "src/utils/EventListener.js",
    "file"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#_queueevent",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-_queueEvent",
    "src/utils/EventListener.js~EventListener#_queueEvent",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#addcontractimplementation",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-addContractImplementation",
    "src/utils/EventListener.js~EventListener#addContractImplementation",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#addeventhandler",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-addEventHandler",
    "src/utils/EventListener.js~EventListener#addEventHandler",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#constructor",
    "class/src/utils/EventListener.js~EventListener.html#instance-constructor-constructor",
    "src/utils/EventListener.js~EventListener#constructor",
    "method"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#contracteventhandlermap",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-contractEventHandlerMap",
    "src/utils/EventListener.js~EventListener#contractEventHandlerMap",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#contractinstances",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-contractInstances",
    "src/utils/EventListener.js~EventListener#contractInstances",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#eventhandlerqueue",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-eventHandlerQueue",
    "src/utils/EventListener.js~EventListener#eventHandlerQueue",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#removecontractinstance",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-removeContractInstance",
    "src/utils/EventListener.js~EventListener#removeContractInstance",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#stopwatchingforevents",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-stopWatchingForEvents",
    "src/utils/EventListener.js~EventListener#stopWatchingForEvents",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#watchforevents",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-watchForEvents",
    "src/utils/EventListener.js~EventListener#watchForEvents",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#watcherinstances",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-watcherInstances",
    "src/utils/EventListener.js~EventListener#watcherInstances",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener.getalleventlogs",
    "class/src/utils/EventListener.js~EventListener.html#static-member-getAllEventLogs",
    "src/utils/EventListener.js~EventListener.getAllEventLogs",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener.geteventlogs",
    "class/src/utils/EventListener.js~EventListener.html#static-member-getEventLogs",
    "src/utils/EventListener.js~EventListener.getEventLogs",
    "member"
  ],
  [
    "src/utils/promisequeue.js",
    "file/src/utils/PromiseQueue.js.html",
    "src/utils/PromiseQueue.js",
    "file"
  ],
  [
    "src/utils/storeproviderwrapper.js",
    "file/src/utils/StoreProviderWrapper.js.html",
    "src/utils/StoreProviderWrapper.js",
    "file"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#_makerequest",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-_makeRequest",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#_makeRequest",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#_storequeue",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-_storeQueue",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#_storeQueue",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#_storeuri",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-_storeUri",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#_storeUri",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#_token",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-_token",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#_token",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#addevidencecontract",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-addEvidenceContract",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#addEvidenceContract",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#constructor",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-constructor-constructor",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#constructor",
    "method"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getcontractbyaddress",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getContractByAddress",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getContractByAddress",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getdisputedataforuser",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getDisputeDataForUser",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getDisputeDataForUser",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getdisputes",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getDisputes",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getDisputes",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getlastblock",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getLastBlock",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getLastBlock",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getuserprofile",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getUserProfile",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getUserProfile",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#istokenvalid",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-isTokenValid",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#isTokenValid",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#marknotificationasread",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-markNotificationAsRead",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#markNotificationAsRead",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#newauthtoken",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-newAuthToken",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#newAuthToken",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#newnotification",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-newNotification",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#newNotification",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#queuereadrequest",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-queueReadRequest",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#queueReadRequest",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#queuewriterequest",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-queueWriteRequest",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#queueWriteRequest",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#setauthtoken",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-setAuthToken",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#setAuthToken",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#setupuserprofile",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-setUpUserProfile",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#setUpUserProfile",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#updatecontract",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-updateContract",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#updateContract",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#updatedisputeprofile",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-updateDisputeProfile",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#updateDisputeProfile",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#updateuserprofile",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-updateUserProfile",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#updateUserProfile",
    "member"
  ],
  [
    "src/utils/web3wrapper.js",
    "file/src/utils/Web3Wrapper.js.html",
    "src/utils/Web3Wrapper.js",
    "file"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#_getnetworkasync",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-_getNetworkAsync",
    "src/utils/Web3Wrapper.js~Web3Wrapper#_getNetworkAsync",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#_getnetworkidifexistsasync",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-_getNetworkIdIfExistsAsync",
    "src/utils/Web3Wrapper.js~Web3Wrapper#_getNetworkIdIfExistsAsync",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#_web3",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-_web3",
    "src/utils/Web3Wrapper.js~Web3Wrapper#_web3",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#blocknumber",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-blockNumber",
    "src/utils/Web3Wrapper.js~Web3Wrapper#blockNumber",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#constructor",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-constructor-constructor",
    "src/utils/Web3Wrapper.js~Web3Wrapper#constructor",
    "method"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#doescontractexistataddressasync",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-doesContractExistAtAddressAsync",
    "src/utils/Web3Wrapper.js~Web3Wrapper#doesContractExistAtAddressAsync",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#fromwei",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-fromWei",
    "src/utils/Web3Wrapper.js~Web3Wrapper#fromWei",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getaccount",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getAccount",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getAccount",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getbalanceinweiasync",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getBalanceInWeiAsync",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getBalanceInWeiAsync",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getblock",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getBlock",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getBlock",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getcoinbase",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getCoinbase",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getCoinbase",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getprovider",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getProvider",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getProvider",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#isaddress",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-isAddress",
    "src/utils/Web3Wrapper.js~Web3Wrapper#isAddress",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#networkidifexists",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-networkIdIfExists",
    "src/utils/Web3Wrapper.js~Web3Wrapper#networkIdIfExists",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#sign",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-sign",
    "src/utils/Web3Wrapper.js~Web3Wrapper#sign",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#tobignumber",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-toBigNumber",
    "src/utils/Web3Wrapper.js~Web3Wrapper#toBigNumber",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#towei",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-toWei",
    "src/utils/Web3Wrapper.js~Web3Wrapper#toWei",
    "member"
  ],
  [
    "src/utils/delegatecalls.js",
    "file/src/utils/delegateCalls.js.html",
    "src/utils/delegateCalls.js",
    "file"
  ],
  [
    "src/utils/deploycontractasync.js",
    "file/src/utils/deployContractAsync.js.html",
    "src/utils/deployContractAsync.js",
    "file"
  ],
  [
    "src/utils/isrequired.js",
    "file/src/utils/isRequired.js.html",
    "src/utils/isRequired.js",
    "file"
  ]
]